name: Build e fazer a publicação da imagem no Docker Hub
on: push
jobs:
    build-and-push:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository
          uses: actions/checkout@v4
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push Docker image
          id: build_push
          uses: docker/build-push-action@v5
          with:
            context: .
            push: true
            tags: ${{ secrets.DOCKER_USERNAME }}/aplicacao-repo:${{ github.sha }}
        - name: Clone manifests repository
          uses: actions/checkout@v4
          with:
            repository: oJotaaa/manifestos-repo
            ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
            path: manifestos-repo
        - name: Update Kubernetes manifest
          run: |
            cd manifestos-repo
            sed -i 's/IMAGE_TAG/${{ github.sha }}/g' deployment.yaml
        - name: Commit and push changes
          run: |
            cd manifestos-repo
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"

            git add deployment.yaml
            git commit -m "Atualiza a imagem para a tag ${{ github.sha }}"
            git push
